version: '3.8'

services:
  redis:
    container_name: tutorilla-cache
    image: redis:7.4.1
    restart: always
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - tutorilla_redis:/data
    networks:
      - tutorilla-network

  postgres:
    container_name: tutorilla-database
    image: postgres:16.5-bookworm
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - tutorilla_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - tutorilla-network

volumes:
  tutorilla_db:
    name: tutorilla_db
  tutorilla_redis:
    name: tutorilla_redis

networks:
  tutorilla-network:
    external: true