services:
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    image: ghcr.io/japolyak/tutorilla-api:latest

  bot:
    build:
      context: .
      dockerfile: bot.Dockerfile
    image: ghcr.io/japolyak/tutorilla-bot:latest

  web-app:
    build:
      context: .
      dockerfile: webapp.Dockerfile
      args:
        VERSION: ${VERSION}
    image: ghcr.io/japolyak/tutorilla-web-app:latest
