version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: api.Dockerfile

  bot:
    build:
      context: .
      dockerfile: bot.Dockerfile

  web-app:
    build:
      context: .
      dockerfile: webapp.Dockerfile
