version: '3.8'

services:
#  bot:
#    container_name: tutorilla-bot
#    build:
#      context: .
#      dockerfile: bot.Dockerfile
#    depends_on:
#      - api
#      - web-app
#
#  api:
#    container_name: tutorilla-api
#    build:
#      context: .
#      dockerfile: api.Dockerfile

  web-app:
    container_name: tutorilla-web-app
    build:
      context: .
      dockerfile: webapp.Dockerfile
    environment:
      - PORT=80
      - VITE_APP_IS_DEV=false
      - VITE_APP_API_URL=http://localhost:8000
    ports:
      - '80:80'
