version: '3.8'

services:
  api:
    container_name: tutorilla-api
    image: ghcr.io/japolyak/tutorilla-api:latest
    env_file:
      - .env
    ports:
      - '${API_PORT}:${API_PORT}'
    networks:
      - tutorilla-network

  bot:
    container_name: tutorilla-bot
    image: ghcr.io/japolyak/tutorilla-bot:latest
    env_file:
      - .env
    ports:
      - '${BOT_PORT}:${BOT_PORT}'
    depends_on:
      - api
    networks:
      - tutorilla-network

  web-app:
    container_name: tutorilla-web-app
    image: ghcr.io/japolyak/tutorilla-web-app:latest
    env_file:
      - .env
    ports:
      - '${WEB_APP_PORT}:${WEB_APP_PORT}'
    depends_on:
      - api
    networks:
      - tutorilla-network

networks:
  tutorilla-network:
    external: true
