version: '3.8'

services:
  redis:
    container_name: tutorilla-cache
    image: redis:alpine
    restart: always
    ports:
      - '127.0.0.1:6379:6379'
    networks:
      - tutorilla-network

  postgres:
    container_name: tutorilla-database
    image: postgres:alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - tutorilla-network

networks:
  tutorilla-network:
    external: true