name: Docker Deplot tests

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Run Database Container
        run: docker start tutorilla-database