name: Deploy

on:
  workflow_run:
    workflows:
      - Build
    types:
      - completed

jobs:
  on-success:
    runs-on: self-hosted

    steps:
      - name: Pull and Run Latest Images
        run: docker-compose -f /home/repos/Tutorilla/src/docker-compose-production.yaml tutorilla up -d
