name: Production

on:
  workflow_run:
    workflows:
      - Build
    types:
      - completed

jobs:
  on-success:
    runs-on: self-hosted

    steps:
      - name: Pull updated images
        run: docker compose -f ${{ secrets.DOCKER_COMPOSE_PATH }}/docker-compose-production.yaml -p tutorilla pull

      - name: Run latest containers
        run: docker compose -f ${{ secrets.DOCKER_COMPOSE_PATH }}/docker-compose-production.yaml -p tutorilla up -d

      - name: Prune unused docker data
        run: docker system prune -af --volumes=false
