name: Test

on:
  push:
    branches:
      - tests

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
#      - name: Check out repository
#        uses: actions/checkout@v3
#        with:
#          fetch-depth: 0

      - name: Fetch tags (if necessary)
        run: git fetch --tags

      - name: Get the latest version tag
        id: get_tag
        run: |
          # Get the latest tag, if available, or set a default version
          tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "Latest tag: $tag"
